### ISSUE TITLE
Issue "Trying to get property 'name' of non-object" {{ Auth::user()->name }}

### ISSUE THREAD

**Issue by dilanjan** [Hujjat/Shopify-Laravel-App#1]
Hi,
When i tried to access any link in navbar other than "Dashboard" I'm getting below error

_Trying to get property 'name' of non-object (View: /var/www/html/resources/views/vendor/shopify-app/layouts/default.blade.php)_

Has anyone experiencing the same error? In the tutorial videos it works perfectly fine. I suspect this is something happening as the routes other than the "Dashboard" not in auth.shopify middleware.

Even after moving all the links in to a route group like below

_Route::group([
    'middleware' => ['auth.shopify']
], function() {
    Route::view('/', 'dashboard');
    Route::view('/products', 'products');
    Route::view('/customers', 'customers');
    Route::view('/settings', 'settings');
});_

After making these changes and after app page load, I am only able to click any of two nav links. When I clicked on the third one it shows shopify App installation page (Enter your shopify domain to login > Install). If i enter the domain correctly it goes to 419 | Page expired.

I have tried three codebases running on docker with ngrok configured. And for the last time i tried to run codebase in this github repo. But still no luck.

Further I checked middleware AuthShopify.php in osiset/laravel-shopify module. I noticed $domain variable in handle function is of type Osiset/ShopifyApp/Objects/Values/ShopDomain in first two navbar link clicks and in the third click its type is Osiset/ShopifyApp/Objects/Values/NullShopDomain. I think there is an issue with the $request but couldn't find an exact cause.

Thanks!! :)

**Comment by xyyolab** [comment]
Maybe you should make sure you have the correct shop information in your database.

**Comment by dilanjan** [comment]
Hi @xyyolab,
I checked they are correct.

**Comment by dilanjan** [comment]
I was able to fix the issue by setting session config's 'same_site' => 'none'. The issue I have mentioned occurs only in firefox. In chrome it works fine. after changing the above mentioned configuration change it'll work in firefox too.
